language: node_js
node_js:
- "0.12"
- "io.js"
sudo: false
cache:
  directories:
  - node_modules
  - vendor/bundle
before_install:
- rvm install 2.2.2
- rvm use 2.2.2
- gem install bundler
- bundle install --path vendor/bundle
before_script:
- $(npm bin)/bower install
- npm test
deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    branch: develop
